### PR TITLE
Create LICENSE.md, so Github displays the license properly

### PR DESCRIPTION
**Pull request by bcye**

### CODE REVIEW

**Comment by Morphan1** [comment]
Neat, thanks!

**Comment by mcmonkey4eva** [comment]
let's not improperly PR things, and also not PR licensing things ever.
Neither of those are cool.
(Nor is pulling a PR without discussion to a repo you don't much of ever contribute to and at last check don't even intend to)

**Comment by Xenmai** [comment]
What they mean is: thanks for your efforts, but licensing is something that probably needs to be discussed by the repo's managers, not pulled from a first time contributor. Anyways thanks for kickstarting the license fix!

**Comment by bcye** [comment]
😆

**Pull request merged**
